name: score-align

channels:
  - conda-forge

dependencies:
  - python=3.6
  - hug
  - librosa
  - lxml
  - numba
  - numpy
  - jpype1
  - audioread
  - requests
  - pip
  - pip:
    - "--editable=git+https://github.com/nficano/pytube.git"
    - pydub
    - gunicorn
